version: '3.7'
services:
  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/app
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: earth_explorer_db
    ports:
      - "3306:3306"
